import type { Metadata } from 'next';
import journey from '../../../resources/journey.json';
import './resume.css';
export const metadata: Metadata={title:'Uday Kumar G — Résumé',description:'AI and machine learning engineer. Education, experience, projects, patents and publications.',openGraph:{title:'Uday Kumar G — Engineer',description:'Ramaiah Institute of Technology · AURIZE · CustomGCApps',type:'profile'}};
export default function Resume(){
 const data={'@context':'https://schema.org','@type':'Person',name:'Uday Kumar G',jobTitle:'Forward Deployed Engineer',worksFor:{'@type':'Organization',name:'CustomGCApps'},alumniOf:{'@type':'CollegeOrUniversity',name:'Ramaiah Institute of Technology'},sameAs:['https://github.com/UDAY2031']};
 return <main className="resume-document"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data).replace(/</g,'\\u003c')}}/><header><a href="/">← Enter the archive</a><p>ENGINEERING · ARTIFICIAL INTELLIGENCE</p><h1>Uday Kumar G</h1><p>Forward Deployed Engineer · Founder · Builder</p><a href="https://github.com/UDAY2031">GitHub ↗</a></header>
 {journey.map(room=><section key={room.id} id={room.id}><p className="resume-index">{String(room.order).padStart(2,'0')} / {room.year}</p><h2>{room.title}</h2><p>{room.place}</p><p>{room.description}</p>{room.pages.map((page,i)=><article key={i}><h3>{page.title}</h3><p>{page.body}</p>{'metric' in page&&<p><strong>{page.metric}</strong></p>}{'year' in page&&<p>{page.year}</p>}{'link' in page&&page.link&&<a href={page.link.url}>{page.link.label}</a>}{'video' in page&&page.video&&<video controls preload="none" playsInline aria-label={`${page.title} demonstration`}><source src={page.video} type="video/mp4"/><a href={page.video}>Watch demonstration</a></video>}</article>)}{!!room.achievements.length&&<ul>{room.achievements.map((a,i)=><li key={i}>{a}</li>)}</ul>}{!!room.techStack.length&&<p><strong>Tools & skills: </strong>{room.techStack.join(' · ')}</p>}{room.links.map(link=><p key={link.url}><a href={link.url}>{link.label} ↗</a></p>)}</section>)}
 <footer><h2>Visitor count & privacy</h2><p>When enabled, the archive counts visitors using a random browser identifier and a daily salted hash of the network address and browser string. The counter does not store or log raw IP addresses. It does not use advertising or third-party analytics. Do Not Track and Global Privacy Control requests are excluded.</p><p>This is an approximate count of browsers that actually render the archive, not a verified count of individual people.</p><a href="/resources/journey.json">Source data ↗</a></footer></main>;
}
